backend:
    name: git-gateway
    repo: nheidner/renergy-js
    branch: master
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: pages-en
      label: Pages (En)
      files:
          - file: 'src/markdown/en/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'TemplateKey',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'en',
                  }
                - {
                      label: 'Page Title',
                      name: 'pageTitle',
                      widget: 'string',
                      hint: 'Modifies the title of the page that will be rendered in the browser - as f.e. seen in the tab bar of the browser',
                  }
                - {
                      label: 'Path',
                      name: 'path',
                      widget: 'string',
                      hint: 'Modifies the path under which the page will be found - Warning: Please only change it, if you know, what you are doing!',
                  }
                - label: Openers
                  name: openers
                  widget: list
                  summary: 'opener'
                  fields:
                      - label: 'Opener Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: 'Heading Link'
                        name: 'heading'
                        widget: object
                        collapsed: true
                        fields:
                            - label: 'Text'
                              name: 'text'
                              widget: markdown
                              buttons: [bold, italic, link]
                              editorComponents: []
                            - { label: 'Href', name: 'href', widget: 'string' }
                      - label: 'More Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }
                - label: Introducing
                  name: introducing
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - { label: Heading, name: heading, widget: string }
                      - label: 'Excerpt'
                        name: 'text'
                        widget: markdown
                        buttons: [bold, italic, link]
                        editorComponents: []
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: 'Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }
                - label: Clients
                  name: clients
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - label: List Of Clients
                        name: clients-list
                        widget: list
                        fields:
                            - label: 'Image'
                              name: 'image'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Image Source',
                                        name: 'source',
                                        widget: 'image',
                                    }
                                  - {
                                        label: 'Alt',
                                        name: 'alt',
                                        widget: 'string',
                                    }
                            - label: 'Link'
                              name: 'link'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Href',
                                        name: 'href',
                                        widget: 'string',
                                    }
                - label: Contact
                  name: contact
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - { label: Heading, name: heading, widget: string }
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: Office Germany
                        name: office-germany
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - label: Address
                              name: address
                              widget: list
                              fields:
                                  - { label: Line, name: line, widget: string }
                      - label: Get In Touch
                        name: get-in-touch
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - {
                                  label: Telephone,
                                  name: telephone,
                                  widget: string,
                              }
                            - label: 'Email'
                              name: 'email'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Text',
                                        name: 'text',
                                        widget: 'string',
                                    }
                                  - {
                                        label: 'Email Address',
                                        name: 'href',
                                        widget: 'string',
                                    }
                      - label: Office UAE
                        name: office-uae
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - label: Address
                              name: address
                              widget: list
                              fields:
                                  - { label: Line, name: line, widget: string }
                      - label: 'Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }
          - file: 'src/markdown/en/our-story.md'
            label: 'Our Story'
            name: 'our-story'
            fields:
                - {
                      label: 'TemplateKey',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'one-column-page',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'en',
                  }
                - {
                      label: 'Page Title',
                      name: 'pageTitle',
                      widget: 'string',
                      hint: 'Modifies the title of the page that will be rendered in the browser - as f.e. seen in the tab bar of the browser',
                  }
                - {
                      label: 'Path',
                      name: 'path',
                      widget: 'string',
                      hint: 'Modifies the path under which the page will be found - Warning: Please only change it, if you know, what you are doing!',
                  }
                - label: 'Opener Image'
                  name: 'opener-image'
                  widget: object
                  collapsed: true
                  required: false
                  fields:
                      - {
                            label: 'Image Source',
                            name: 'source',
                            widget: 'image',
                            required: false,
                        }
                      - {
                            label: 'Alt',
                            name: 'alt',
                            widget: 'string',
                            required: false,
                        }
                - label: 'Page Content'
                  name: 'content'
                  widget: markdown
                  buttons:
                      [
                          bold,
                          italic,
                          link,
                          heading-one,
                          heading-two,
                          heading-three,
                          bulleted-list,
                          numbered-list,
                      ]
                  editorComponents: [image]
                - label: Team
                  name: team-list
                  widget: list
                  collapsed: true
                  fields:
                      - { label: Name, name: name, widget: string }
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - { label: Role, name: role, widget: string }
    - name: 'one-column'
      label: 'One Column Pages (En)'
      label_singular: Page
      folder: 'src/markdown/en/one-column-pages'
      field_identifier: path
      create: true
      fields:
          - {
                label: 'TemplateKey',
                name: 'templateKey',
                widget: 'hidden',
                default: 'one-column-page',
            }
          - { label: 'Locale', name: 'locale', widget: 'hidden', default: 'en' }
          - {
                label: 'Page Title',
                name: 'pageTitle',
                widget: 'string',
                hint: 'Modifies the title of the page that will be rendered in the browser - as f.e. seen in the tab bar of the browser',
            }
          - {
                label: 'Path',
                name: 'path',
                widget: 'string',
                hint: 'Modifies the path under which the page will be found - Warning: Please only change it, if you know, what you are doing!',
            }
          - label: 'Opener Image'
            name: 'opener-image'
            widget: object
            collapsed: true
            required: false
            fields:
                - {
                      label: 'Image Source',
                      name: 'source',
                      widget: 'image',
                      required: false,
                  }
                - {
                      label: 'Alt',
                      name: 'alt',
                      widget: 'string',
                      required: false,
                  }
          - label: 'Page Content'
            name: 'content'
            widget: markdown
            buttons:
                [
                    bold,
                    italic,
                    link,
                    heading-one,
                    heading-two,
                    heading-three,
                    bulleted-list,
                    numbered-list,
                ]
            editorComponents: [image]

    - name: pages-de
      label: Pages (De)
      files:
          - file: 'src/markdown/pages/de/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'de',
                  }
                - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
                - { label: 'Path', name: 'path', widget: 'string' }
