backend:
    name: github
    repo: nheidner/renergy-js
    branch: master
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: en
      label: English
      files:
          - file: 'src/markdown/pages/en/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'en',
                  }
                - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
                - { label: 'Path', name: 'path', widget: 'string' }
                - label: Openers
                  name: openers
                  widget: list
                  fields:
                      - label: 'Opener Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: 'Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }
                - label: Introducing
                  name: introducing
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - { label: Heading, name: heading, widget: string }
                      - { label: Excerpt, name: text, widget: markdown }
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: 'Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }
                - label: Clients
                  name: clients
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - label: List Of Clients
                        name: clients-list
                        widget: list
                        fields:
                            - label: 'Image'
                              name: 'image'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Image Source',
                                        name: 'source',
                                        widget: 'image',
                                    }
                                  - {
                                        label: 'Alt',
                                        name: 'alt',
                                        widget: 'string',
                                    }
                            - label: 'Link'
                              name: 'link'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Text',
                                        name: 'text',
                                        widget: 'string',
                                    }
                                  - {
                                        label: 'Href',
                                        name: 'href',
                                        widget: 'string',
                                    }
                - label: Contact
                  name: contact
                  widget: object
                  collapsed: true
                  fields:
                      - { label: Topic, name: topic, widget: string }
                      - { label: Heading, name: heading, widget: string }
                      - label: 'Image'
                        name: 'image'
                        widget: object
                        collapsed: true
                        fields:
                            - {
                                  label: 'Image Source',
                                  name: 'source',
                                  widget: 'image',
                              }
                            - { label: 'Alt', name: 'alt', widget: 'string' }
                      - label: Office Germany
                        name: office-germany
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - label: Address
                              name: address
                              widget: list
                              fields:
                                  - { label: Line, name: line, widget: string }
                      - label: Get In Touch
                        name: get-in-touch
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - {
                                  label: Telephone,
                                  name: telephone,
                                  widget: string,
                              }
                            - label: 'Email'
                              name: 'email'
                              widget: object
                              collapsed: true
                              fields:
                                  - {
                                        label: 'Text',
                                        name: 'text',
                                        widget: 'string',
                                    }
                                  - {
                                        label: 'Email Address',
                                        name: 'href',
                                        widget: 'string',
                                    }
                      - label: Office UAE
                        name: office-uae
                        widget: object
                        collapsed: true
                        fields:
                            - { label: Heading, name: heading, widget: string }
                            - label: Address
                              name: address
                              widget: list
                              fields:
                                  - { label: Line, name: line, widget: string }
                      - label: 'Link'
                        name: 'link'
                        widget: object
                        collapsed: true
                        fields:
                            - { label: 'Text', name: 'text', widget: 'string' }
                            - { label: 'Href', name: 'href', widget: 'string' }

    - name: de
      label: Deutsch
      files:
          - file: 'src/markdown/pages/de/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'de',
                  }
                - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
                - { label: 'Path', name: 'path', widget: 'string' }
