backend:
    name: github
    repo: nheidner/renergy-js
    branch: master
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: en
      label: English
      files:
          - file: 'src/markdown/pages/en/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'en',
                  }
                - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
                - { label: 'Path', name: 'path', widget: 'string' }

    - name: de
      label: Deutsch
      files:
          - file: 'src/markdown/pages/de/index.md'
            label: 'Home'
            name: 'index'
            fields:
                - {
                      label: 'Template Key',
                      name: 'templateKey',
                      widget: 'hidden',
                      default: 'index',
                  }
                - {
                      label: 'Locale',
                      name: 'locale',
                      widget: 'hidden',
                      default: 'de',
                  }
                - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
                - { label: 'Path', name: 'path', widget: 'string' }
